Adds Tweet-Recommendation Quickstart
spiceai/quickstarts pull request #46
Opened 2021-10-11 04:47 UTC by Mcilie

I still need to add the actual pod to the registry, but what is necessary for the quick-start is right in this PR

2021-10-11 06:12 UTC, phillipleblanc commented on tweetrec/README.md
> +Let's use a brand that has a very active twitter presence
It might be useful to start with a problem statement on why someone would want to do this.

2021-10-11 06:13 UTC, phillipleblanc commented on tweetrec/README.md
> +In the Spice.ai runtime terminal, you will observe the runtime loading the CSV from `spicepods/data/new_NZXT_tweets.csv` and starting to train!
I wouldn't call the data field `new_NZXT_tweets`. Consider renaming to something more generic like `tweet_activity.csv`

2021-10-11 06:22 UTC, phillipleblanc commented on tweetrec/README.md
> +Now, save the file. You should observe a new training run begin in the Spice.ai runtime terminal. You can also manually start a training run using this command.
```suggestion
You should observe a new training run begin in the Spice.ai runtime terminal. You can also manually start a training run using this command.
```

It isn't clear from these instructions which file the user will need to save. The runtime should automatically start training whenever the `spice add` command completes.

2021-10-11 06:23 UTC, phillipleblanc commented on tweetrec/README.md
> +```
```suggestion
```json
{
    "start":1633694400,
    "end":1633824000,
    "action":"tweet",
    "confidence":0.851,
    "tag":"latest"
}
```
```

Remove the extra line

2021-10-11 06:24 UTC, phillipleblanc submitted a review, later dismissed
Looking good! Just a few minor tweaks. Also, please change the title of the PR to describe the contents more accurately. Right now the word twitter doesn't appear in it.

2021-10-11 11:39 UTC, Mcilie commented on tweetrec/README.md
> +In the Spice.ai runtime terminal, you will observe the runtime loading the CSV from `spicepods/data/new_NZXT_tweets.csv` and starting to train!
Okay, ill add the changes you suggested soon

2021-10-11 18:29 UTC, haardvark requested changes
Let's hold off on merging this until comments are addressed, registry changes are present, and we have an E2E test that validates things are working correctly.

2021-10-11 18:29 UTC, haardvark commented on tweetrec/README.md
> +Let's use a brand that has a very active twitter presence
Avoid using "let's/we" language in docs.

2021-10-11 18:29 UTC, haardvark commented on tweetrec/README.md
> +A basic bot to recommend twitter activity for brand marketing accounts
Twitter is a proper noun and should be capitalized throughout the docs.   I'd also make this first "Twitter" ref a link to Twitter.

2021-10-11 18:29 UTC, haardvark commented on tweetrec/README.md
> +Congratulations! You've successfully trained a model that provides real-time recommendations for twitter marketing accounts based off of performance of previous tweets and retweets
Missing period

2021-10-11 18:29 UTC, haardvark commented on tweetrec/README.md
> +If you were to extend this example to a real-world application, the next steps might be to replace the static CSV data with live streaming data and to further develop the reward functions to train a
When you have it, next steps should lead to building on this with your sample

2021-10-15 21:53 UTC, haardvark approved these changes

2021-10-15 21:54 UTC, merged